### ISSUE TITLE
毎回違うreasonが返ってくる

### ISSUE THREAD

**Issue by m-walk** [azumakuniyuki/Sisimai#56]
以下のバウンスメールを食わせると毎回違うreasonが返ってきます。（networkerrorかexpired）

From MAILER-DAEMON  Fri Jan 1 00:0:00 2015
Return-Path: <>
X-Original-To: xxxxxx@xxxxxx
Delivered-To: xxxxxx@xxxxxx
Received: from xxxxxx (xxxxxx)
	by xxxxxx (Postfix) with SMTP id XXXXX
	for <xxxxxx@xxxxxx>; Fri, 1 Jan 2015 00:00:00 +0900 (JST)
Received: (qmail XXXXX invoked for bounce); 1 Jan 2015 00:00:00 +0900
Date: 1 Jan 2015 00:0:00 +0900
From: MAILER-DAEMONxxxxxx
To: xxxxxx@xxxxxx
Subject: failure notice

Hi. This is the qmail-send program at xxx.
I'm afraid I wasn't able to deliver your message to the following addresses.
This is a permanent error; I've given up. Sorry it didn't work out.

<xxx@xxx>:
Sorry, I wasn't able to establish an SMTP connection. (#4.4.1)
I'm not going to try again; this message has been in the queue too long.

--- Below this line is a copy of the message.

**Comment by azumakuniyuki** [comment]
ご連絡有り難う御座います、上記のメールを少し加工(下記)して解析試験に欠けてみたところ、確かに"expired"と"networkerror"がランダムに現れる現象を確認出来ました。

```
From MAILER-DAEMON Fri Jan 1 00:0:00 2015
Return-Path: <>
X-Original-To: shironeko@example.ad.jp
Delivered-To: shironeko@example.ad.jp
Received: from host (mta1)
    by xxxxxx (Postfix) with SMTP id F00000
    for shironeko@example.ad.jp; Fri, 1 Jan 2015 00:00:00 +0900 (JST)
Received: (qmail host invoked for bounce); 1 Jan 2015 00:00:00 +0900
Date: 1 Jan 2015 00:00:00 +0900
From: MAILER-DAEMON@example.jp
To: shironeko@example.ad.jp
Subject: failure notice

Hi. This is the qmail-send program at xxx.
I'm afraid I wasn't able to deliver your message to the following addresses.
This is a permanent error; I've given up. Sorry it didn't work out.

<kijitora@example.jp>:
Sorry, I wasn't able to establish an SMTP connection. (#4.4.1)
I'm not going to try again; this message has been in the queue too long.

--- Below this line is a copy of the message.
```
修正が完了したら改めて報告致します。

**Comment by azumakuniyuki** [comment]
Commit e7a31d70ba28759e48cf0eaf88946f87202e891e でコードを修正、Sisimai 4.1.17としてリリースしました。

原因は、新しい目のPerlではkeys %hashを実行した際の順序が実行の度にランダムになる点によるもので、"networkerror"と"expired"双方の正規表現に一致する文字列を含むメールを解析すると、実行毎に"reason"の値が異なって現れていました。

**Comment by m-walk** [comment]
ありがとうございます。
自分もハッシュのランダム化はたまに忘れます…。
